// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearALl() {
  return window['go']['main']['App']['ClearALl']();
}

export function ConvertImagesToPDF(arg1) {
  return window['go']['main']['App']['ConvertImagesToPDF'](arg1);
}

export function ConvertPDFToImages(arg1) {
  return window['go']['main']['App']['ConvertPDFToImages'](arg1);
}

export function ExtractPDFPages() {
  return window['go']['main']['App']['ExtractPDFPages']();
}

export function GetFiles(arg1, arg2) {
  return window['go']['main']['App']['GetFiles'](arg1, arg2);
}

export function GetFolder() {
  return window['go']['main']['App']['GetFolder']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MergeFiles(arg1) {
  return window['go']['main']['App']['MergeFiles'](arg1);
}

export function MergePDFs(arg1) {
  return window['go']['main']['App']['MergePDFs'](arg1);
}

export function OptimizeImages(arg1) {
  return window['go']['main']['App']['OptimizeImages'](arg1);
}

export function OptimizePDF(arg1) {
  return window['go']['main']['App']['OptimizePDF'](arg1);
}

export function ProcessFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProcessFiles'](arg1, arg2, arg3);
}

export function RemoveFile(arg1) {
  return window['go']['main']['App']['RemoveFile'](arg1);
}
