// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearALl():Promise<void>;

export function ConvertImagesToPDF(arg1:string):Promise<void>;

export function ConvertPDFToImages(arg1:string):Promise<void>;

export function ExtractPDFPages():Promise<void>;

export function GetFiles(arg1:string,arg2:string,arg3:boolean):Promise<Array<string>>;

export function GetFolder():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function MergeFiles(arg1:Array<string>):Promise<string>;

export function MergePDFs(arg1:string):Promise<void>;

export function OptimizeImages(arg1:number):Promise<void>;

export function OptimizePDF(arg1:string):Promise<void>;

export function ProcessFiles(arg1:string,arg2:string,arg3:number):Promise<void>;

export function RemoveFile(arg1:string):Promise<void>;
